[users]
Public_Services_Department = "P$D!9v8rQeZ#2025"
Ras_Al_Khaimah_Municipality = "R@kM#7xYbL%2025"
Sheikh_Saud_Center = "S$SC^4nTq8&2025"
Sheikh_Saqr_Center = "SSQ*6uWm2!2025"
Executive_Council = "ExC^Adm!n#2025"
